import json
import re
import sys
from collections import defaultdict

sys.stdout.reconfigure(encoding='utf-8')

with open('data/products.json', 'r', encoding='utf-8') as f:
    products = json.load(f)

# Master Brand Definitions
# Format: (Brand Name, [Keywords / Patterns], [Negative / Exclude Keywords])

BRAND_RULES = [
    # Gıda / Bisküvi / Çikolata / İçecek
    ('ÜLKER', ['ÜLKER', 'ULKER', 'ALBENİ', 'ALBENI', 'ÇOKONAT', 'COKONAT', 'HALLEY', 'HANIMELLER', 'RONDO', 'BİSKREM', 'BISKREM', 'CANPASTA', 'ÇİZİ', 'CIZI', 'ÇİZİVİÇ', 'İKRAM', 'IKRAM', 'DANKEK', 'DİDO', 'DIDO', 'PROBİS', 'PROBIS', 'OLALA', 'ALPELLA', 'ONEP', 'ÇOKOMEL', 'ÇOKOKREM', 'ÇOKOPRENS', 'HAYLAYF', 'İNCİR REÇELİ', 'ALTINBAŞAK', 'TAÇ KRAKER', 'ASLAN KRAL KEK'], ['ETİ', 'ŞÖLEN']),
    ('ETİ', ['ETİ', 'ETI', 'CRAX', 'BENİMO', 'BENIMO', 'BURÇAK', 'BURCAK', 'TUTKU', 'GONG', 'HOŞBEŞ', 'HOSBES', 'KOMBO', 'CİCİBEBE', 'CICI BEBE', 'CİCİ BEBE', 'KARAM', 'WANTED', 'MAXIMUS', 'DUDOMI', 'TOPKEK', 'AŞK ALEVİ', 'POPS MEKSİKA', 'LİFALİF', 'LIFALIF'], ['DİŞ ETİ', 'DIS ETI', 'KUZU ETİ', 'SIĞIR ETİ', 'TAVUK ETİ', 'HİNDİ ETİ', 'DANA ETİ', 'CİN MISIR', 'CIN MISIR', 'BEŞLER', 'FELİX', 'ORAL B', 'SENSODYNE', 'VATAN', 'SEBİL', 'DOĞUŞ', 'ŞÖLEN', 'MAYLO']),
    ('ŞÖLEN', ['ŞÖLEN', 'SOLEN', 'LUPPO', 'OZMO', 'BOOMBASTIC', 'BİSCOLATA', 'BISCOLATA', 'PAPİTA', 'PAPITA', 'MILANGO', 'NUTYMAX', 'GRETA', 'OCTAVIA', 'WISH', 'AMADA', 'CHOCO DAN’S'], []),
    ('NESTLE', ['NESTLE', 'NESCAFE', 'NESCAFE GOLD', 'NESQUIK', 'NESGUIK', 'KITKAT', 'CRUNCH', 'DAMAK', 'NESFIT', 'NESFİT', 'LION BAR', 'CHOKELLA', 'COKO KRONCH'], []),
    ('ALGİDA', ['ALGİDA', 'ALGIDA', 'MAGNUM', 'CORNETTO', 'NOGGER', 'MAX DONDURMA', 'TWISTER', 'CARTE D\'OR', 'MARAŞ USULÜ', 'BOOM BOOM', 'CALIPPO', 'FRUTTARE'], []),
    ('TORKU', ['TORKU', 'BANADA', 'FREMA', 'NO ON', 'MINIKI', 'RUŞEYMLİ'], []),
    ('DOĞUŞ', ['DOĞUŞ', 'DOGUS', 'DOĞUŞ ÇAY', 'DOĞUŞ FORM', 'PATOS', 'CİPSO', 'CIPSO', 'ÇEREZZA', 'CEREZZA'], []),
    ('ÇAYKUR', ['ÇAYKUR', 'CAYKUR', 'DİDİ', 'DIDI', 'TİRYAKİ', 'RİZE TURİST', 'KAMELYA', 'FİLİZ ÇAY', 'ALTINBAŞ'], []),
    ('LİPTON', ['LİPTON', 'LIPTON', 'ICE TEA', 'İCE TEA', 'YELLOW LABEL', 'DOĞU KARADENİZ'], []),
    ('DOĞADAN', ['DOĞADAN', 'DOGADAN', 'BÜYÜLÜ BOHÇA', 'GİZLİ BAHÇE'], []),
    ('OFÇAY', ['OFÇAY', 'OFCAY', 'EFSANE', 'ŞERANE', 'HAZİNE'], []),
    ('SÜTAŞ', ['SÜTAŞ', 'SUTAS', 'SÜTAŞ SÜT', 'SÜTAŞ KAŞAR', 'SÜTAŞ AYRAN', 'SÜTAŞ TEREYAĞ', 'SÜTAŞ YOĞURT', 'BÜYÜMİX', 'KAF KEFİR'], []),
    ('PINAR', ['PINAR', 'PINAR SÜT', 'PINAR SUCUK', 'PINAR SOS', 'PINAR KREMA', 'PINAR LABNE', 'PINAR SU', 'KİDO', 'AÇ BİTİR'], ['PINARBAŞI']),
    ('İÇİM', ['İÇİM', 'ICIM', 'İÇİM SÜT', 'İÇİM KAŞAR', 'İÇİM AYRAN', 'İÇİM ŞEF', 'İÇİM LABNE', 'İÇİM KEFİR', 'FIT SÜT'], []),
    ('EKER', ['EKER', 'EKER AYRAN', 'EKER SÜT', 'EKER YOĞURT', 'EKER KEFİR', 'EKER TATLI', 'EKER DONDURMA'], ['DR. OETKER', 'DR OETKER', 'ŞEKER', 'SEKER']),
    ('SEK', ['SEK', 'SEK SÜT', 'SEK AYRAN', 'SEK YOĞURT', 'SEK TEREYAĞ', 'SEK KAZANDİBİ'], []),
    ('DANONE', ['DANONE', 'DANİNO', 'DANINO', 'DOKİDO', 'ACTİVİA', 'ACTIVIA'], []),
    ('SÜPERFRESH', ['SÜPERFRESH', 'SUPERFRESH'], []),
    ('DİMES', ['DİMES', 'DIMES', 'DİMES COOL', 'SIKMA PORTAKAL', 'DİMES MİX'], []),
    ('CAPPY', ['CAPPY'], []),
    ('COCA-COLA', ['COCA-COLA', 'COCA COLA', 'COKE', 'FANTA', 'SPRITE', 'SCHWEPPES', 'FUSE TEA', 'DAMLA SU', 'DAMLA MİNERA'], []),
    ('PEPSİ', ['PEPSİ', 'PEPSI', 'FRUKO', 'YEDİGÜN', 'YEDIGUN', '7UP', 'LIPTON ICE TEA', 'TROPICANA'], []),
    ('RED BULL', ['RED BULL', 'REDBULL', 'RED BUL'], []),
    ('MONSTER', ['MONSTER ENERGY', 'MONSTER'], []),
    ('BEYPAZARI', ['BEYPAZARI'], []),
    ('KIZILAY', ['KIZILAY', 'KIZILAY SODA'], []),
    ('KINIK', ['KINIK', 'KINIK SODA'], []),
    ('SARIKIZ', ['SARIKIZ'], []),
    ('AVŞAR', ['AVŞAR', 'AVSAR', 'AVŞAR SODA', 'AVSAR SODA'], []),
    ('FREŞA', ['FREŞA', 'FRESA'], []),
    ('ULUDAĞ', ['ULUDAĞ', 'ULUDAG', 'ULUDAĞ GAZOZ', 'FRUTTİ', 'FRUTTI'], []),
    ('SIRMA', ['SIRMA', 'SIRMAGRUP', 'SIRMA SU', 'SIRMA SODA'], []),
    ('ERİKLİ', ['ERİKLİ', 'ERIKLI'], []),
    ('BUZDAĞI', ['BUZDAĞI', 'BUZDAGI'], []),
    ('HAYAT', ['HAYAT SU', 'HAYAT'], []),
    ('İNİŞDİBİ', ['İNİŞDİBİ', 'INISDIBI'], []),
    ('ÖZKAYNAK', ['ÖZKAYNAK', 'OZKAYNAK'], []),
    ('TAÇ MAHAL', ['TAÇ MAHAL', 'TAC MAHAL', 'TAÇMAHAL'], []),
    ('KAHVE DÜNYASI', ['KAHVE DÜNYASI', 'KAHVE DUNYASI', 'NELLO', 'TAMBOL'], []),
    ('MEHMET EFENDİ', ['MEHMET EFENDİ', 'MEHMET EFENDI', 'KURUKAHVECİ'], []),
    ('JACOBS', ['JACOBS', 'MONARCH'], []),
    ('TCHIBO', ['TCHIBO'], []),
    ('LAVAZZA', ['LAVAZZA'], []),
    ('DAVIDOFF', ['DAVIDOFF KAHVE'], []),
    ('DORİTOS', ['DORİTOS', 'DORITOS'], []),
    ('LAYS', ['LAYS', 'LAY\'S'], []),
    ('RUFFLES', ['RUFFLES'], []),
    ('CHEETOS', ['CHEETOS'], []),
    ('PATOS', ['PATOS'], []),
    ('CİPSO', ['CİPSO', 'CIPSO'], []),
    ('ÇEREZZA', ['ÇEREZZA', 'CEREZZA'], []),
    ('PRİNGLES', ['PRİNGLES', 'PRINGLES'], []),
    ('MASTER', ['MASTER POTATO', 'MASTER FARM', 'MASTER NUT'], []),
    ('TADIM', ['TADIM'], []),
    ('PEYMAN', ['PEYMAN', 'BAHÇEDEN', 'ÇİTLEYİK', 'DOR Leo', 'NUTZZ'], []),
    ('AYPOP', ['AYPOP', 'AY-POP'], []),
    ('PEYMAN', ['PEYMAN'], []),
    ('HARİBO', ['HARİBO', 'HARIBO', 'CHAMALLOWS', 'GOLD BÄREN'], []),
    ('BEBETO', ['BEBETO'], []),
    ('JELİBON', ['JELİBON', 'JELIBON'], []),
    ('KENT', ['KENT SAKIZ', 'KENT ŞEKER', 'OLİPS', 'OLIPS', 'FALIM', 'FIRST SAKIZ', 'FİRST SAKIZ', 'VİVİDENT', 'MENTOS', 'TOFFEE', 'MISSBON', 'TİPİTİP', 'CHUPA CHUPS'], ['KENT SİGARA', 'KENT D-RANGE', 'KENT SLIMS']),
    ('VİVİDENT', ['VİVİDENT', 'VIVIDENT'], []),
    ('FALIM', ['FALIM'], []),
    ('FİRST', ['FİRST', 'FIRST SAKIZ', 'FIRST 60'], []),
    ('MENTOS', ['MENTOS'], []),
    ('DR.OETKER', ['DR.OETKER', 'DR. OETKER', 'DR OETKER', 'OETKER'], []),
    ('KENT BORİNGER', ['KENT BORİNGER', 'KENT BORINGER', 'BORİNGER', 'BORINGER'], []),
    ('BİZİM', ['BİZİM', 'BIZIM', 'BİZİM YAĞ', 'BİZİM MUTFAK', 'BİZİM ÇORBA'], []),
    ('KNORR', ['KNORR'], []),
    ('MAGGI', ['MAGGI'], []),
    ('CALVE', ['CALVE'], []),
    ('HEINZ', ['HEINZ'], []),
    ('TAT', ['TAT SALÇA', 'TAT KETÇAP', 'TAT MAYONEZ', 'TAT GARNİTÜR', 'TAT TURŞU', 'TAT MISIR', 'TAT BEZELYE', 'TAT FASULYE', 'TAT BARBUNYA', 'TAT NOHUT', 'TAT DOMATES', 'TAT SOS'], []),
    ('TAMEK', ['TAMEK'], []),
    ('BURCU', ['BURCU'], []),
    ('ÖNCÜ', ['ÖNCÜ', 'ONCU'], []),
    ('TUKAS', ['TUKAŞ', 'TUKAS'], []),
    ('KOMİLİ', ['KOMİLİ', 'KOMILI'], []),
    ('YUDUM', ['YUDUM', 'EGEMDEN', 'KIZARTMA USTASI'], []),
    ('KRİSTAL', ['KRİSTAL YAĞ', 'KRISTAL YAG', 'KRİSTAL ZEYTİNYAĞI'], []),
    ('ORUÇOĞLU', ['ORUÇOĞLU', 'ORUCOGLU'], []),
    ('TARİŞ', ['TARİŞ', 'TARIS'], []),
    ('KOSKA', ['KOSKA'], []),
    ('SEYİDOĞLU', ['SEYİDOĞLU', 'SEYIDOGLU', 'SEYİDOGLU', 'SEYYİDOĞLU'], []),
    ('BALPARMAK', ['BALPARMAK'], []),
    ('ANAVARZA', ['ANAVARZA'], []),
    ('BİLLUR', ['BİLLUR', 'BILLUR'], []),
    ('SALINA', ['SALİNA', 'SALINA'], []),
    ('BAĞDAT', ['BAĞDAT', 'BAGDAT'], []),
    ('ARİFOĞLU', ['ARİFOĞLU', 'ARIFOGLU'], []),
    ('KOROPLAST', ['KOROPLAST'], []),
    ('COOK', ['COOK STREÇ', 'COOK PİŞİRME', 'COOK BUZDOLABI'], []),
    ('PAREX', ['PAREX'], []),
    ('VİLEDA', ['VİLEDA', 'VILEDA'], []),
    ('BANAT', ['BANAT'], []),
    ('SCOTCH-BRITE', ['SCOTCH BRITE', 'SCOTCH-BRITE', 'SCOTCH'], []),
    ('FAIRY', ['FAIRY'], []),
    ('PRIL', ['PRIL', 'PRİL'], []),
    ('FINISH', ['FINISH', 'CALGONIT'], []),
    ('CALGON', ['CALGON'], []),
    ('DOMESTOS', ['DOMESTOS'], []),
    ('CIF', ['CIF', 'CİF'], []),
    ('ACE', ['ACE ÇAMAŞIR'], []),
    ('PORÇÖZ', ['PORÇÖZ', 'PORCOZ', 'PORCÖZ'], []),
    ('CAMSİL', ['CAMSİL', 'CAMSIL'], []),
    ('MR.MUSCLE', ['MR.MUSCLE', 'MR MUSCLE', 'MR. MUSCLE'], []),
    ('BİNGO', ['BİNGO', 'BINGO'], []),
    ('ARIEL', ['ARIEL', 'ARİEL'], []),
    ('OMO', ['OMO'], []),
    ('PERSIL', ['PERSIL', 'PERSİL'], []),
    ('PERWOLL', ['PERWOLL'], []),
    ('TURSİL', ['TURSİL', 'TURSIL'], []),
    ('ALO', ['ALO DETERJAN', 'ALO'], []),
    ('YUMOŞ', ['YUMOŞ', 'YUMOS'], []),
    ('VERNEL', ['VERNEL'], []),
    ('SELPAK', ['SELPAK'], []),
    ('SOLO', ['SOLO'], []),
    ('PAPİA', ['PAPİA', 'PAPIA'], []),
    ('FAMİLİA', ['FAMİLİA', 'FAMILIA'], []),
    ('MAYLO', ['MAYLO'], []),
    ('TENO', ['TENO'], []),
    ('SOFIA', ['SOFIA', 'SOFİA'], []),
    ('SLEEPY', ['SLEEPY'], []),
    ('MOLFİX', ['MOLFİX', 'MOLFIX'], []),
    ('PRİMA', ['PRİMA', 'PRIMA', 'PAMPERS'], []),
    ('CANBEBE', ['CANBEBE'], []),
    ('ORKİD', ['ORKİD', 'ORKID', 'ALWAYS'], []),
    ('KOTEX', ['KOTEX'], []),
    ('MOLPED', ['MOLPED'], []),
    ('NİVEA', ['NİVEA', 'NIVEA'], []),
    ('DOVE', ['DOVE'], []),
    ('DURU', ['DURU SABUN', 'DURU DUŞ', 'DURU ŞAMPUAN', 'DURU'], []),
    ('PALMOLİVE', ['PALMOLİVE', 'PALMOLIVE'], []),
    ('HACIOŞMANOĞLU', ['HACIOŞMANOĞLU'], []),
    ('HACI ŞAKİR', ['HACI ŞAKİR', 'HACISAKIR', 'HACI SAKIR'], []),
    ('ARKO', ['ARKO', 'ARKO MEN', 'ARKO NEM'], []),
    ('ELİDOR', ['ELİDOR', 'ELIDOR', 'SUNSILK'], []),
    ('PANTENE', ['PANTENE'], []),
    ('HEAD&SHOULDERS', ['HEAD&SHOULDERS', 'HEAD & SHOULDERS', 'HEAD AND SHOULDERS', 'HEAD&SHOULD.'], []),
    ('CLEAR', ['CLEAR ŞAMPUAN', 'CLEAR MEN', 'CLEAR'], []),
    ('BLENDAX', ['BLENDAX'], []),
    ('İPEK', ['İPEK ŞAMPUAN', 'IPEK SAMPUAN', 'İPEK'], []),
    ('GLISS', ['GLISS', 'GLİSS'], []),
    ('SYOSS', ['SYOSS'], []),
    ('BIOBLAS', ['BIOBLAS', 'BİOBLAS'], []),
    ('BİOXCİN', ['BİOXCİN', 'BIOXCIN'], []),
    ('DALİN', ['DALİN', 'DALIN'], []),
    ('COLGATE', ['COLGATE'], []),
    ('SENSODYNE', ['SENSODYNE', 'SENSODAYN'], []),
    ('ORAL-B', ['ORAL-B', 'ORAL B', 'ORALB'], []),
    ('İPANA', ['İPANA', 'IPANA'], []),
    ('SIGNAL', ['SİGNAL', 'SIGNAL'], []),
    ('PARODONTAX', ['PARODONTAX'], []),
    ('LİSTERİNE', ['LİSTERİNE', 'LISTERINE'], []),
    ('GİLLETTE', ['GİLLETTE', 'GILLETTE', 'GİLETTE', 'GILETTE', 'VENUS', 'BLUE 3', 'BLUE II', 'MACH 3', 'FUSION'], []),
    ('DERBY', ['DERBY'], []),
    ('BİC', ['BİC', 'BIC'], []),
    ('DURACELL', ['DURACELL'], []),
    ('PANASONİC', ['PANASONİC', 'PANASONIC'], []),
    ('ENERGIZER', ['ENERGIZER', 'ENERGİZER'], []),
    ('TOSHIBA', ['TOSHIBA'], []),
    ('PHILIPS', ['PHILIPS'], []),
    ('VARTA', ['VARTA'], []),
    ('DUREX', ['DUREX'], []),
    ('OKEY', ['OKEY PRESERVATİF', 'OKEY'], []),
    ('RAİD', ['RAİD', 'RAID'], []),
    ('OFF!', ['OFF SİNEK', 'OFF!'], []),
    ('DETAN', ['DETAN'], []),
    ('SİNKAV', ['SİNKAV', 'SINKAV'], []),
    ('BOĞAZİÇİ', ['BOĞAZİÇİ KOLONYA', 'BOGAZICI KOLONYA', 'BOĞAZİÇİ', 'BOGAZICI'], []),
    ('EYÜP SABRİ TUNCER', ['EYÜP SABRİ TUNCER', 'EYUP SABRI TUNCER', 'EST 1923'], []),
    ('PEREJA', ['PEREJA'], []),
    ('SELİN', ['SELİN KOLONYA', 'SELIN KOLONYA', 'SELİN', 'SELIN'], []),
    ('DİMES', ['DİMES'], []),
    ('FİLİZ', ['FİLİZ MAKARNA', 'FİLİZ M.', 'FILIZ'], []),
    ('BARİLLA', ['BARİLLA', 'BARILLA'], []),
    ('NUDO', ['NUDO'], []),
    ('İNDOMİE', ['İNDOMİE', 'INDOMIE', 'INDOMİE', 'INDOMIES', 'İNDOMİES'], []),
    ('MUTLU', ['MUTLU MAKARNA', 'MUTLU'], []),
    ('Nuh\'un Ankara', ['NUHUN ANKARA', 'NUH UN ANKARA', 'NUH\'UN ANKARA'], []),
    ('BEŞLER', ['BEŞLER', 'BESLER'], []),
    ('ŞAHİN', ['ŞAHİN SUCUK', 'SAHIN SUCUK', 'ŞAHİN', 'SAHIN'], []),
    ('NAMET', ['NAMET', 'MARET'], []),
    ('POLONEZ', ['POLONEZ'], []),
    ('CUMHURİYET', ['CUMHURİYET SUCUK', 'CUMHURIYET SUCUK', 'CUMHURİYET'], []),
    ('COŞKUN', ['COŞKUN SUCUK', 'COSKUN SUCUK', 'COŞKUN', 'COSKUN'], []),
    ('APİKOĞLU', ['APİKOĞLU', 'APIKOGLU'], []),
    ('ÇAPANOĞLU', ['ÇAPANOĞLU', 'CAPANOGLU'], []),
    ('BAŞYAZICI', ['BAŞYAZICI', 'BASYAZICI'], []),
    ('ERŞAN', ['ERŞAN', 'ERSAN'], []),
    ('ŞAHBAZ', ['ŞAHBAZ', 'SAHBAZ'], []),
    ('DANET', ['DANET'], []),
    ('GEDİK', ['GEDİK', 'GEDIK'], []),
    ('ŞENPİLİÇ', ['ŞENPİLİÇ', 'SENPILIC'], []),
    ('BEYPİLİÇ', ['BEYPİLİÇ', 'BEYPILIC'], []),
    ('KORPİLİÇ', ['KORPİLİÇ', 'KORPILIC', 'KOR PİLİÇ'], []),
    ('BANVİT', ['BANVİT', 'BANVIT'], []),
    ('LEZİTA', ['LEZİTA', 'LEZITA'], []),
    ('ER PİLİÇ', ['ER PİLİÇ', 'ERPİLİÇ', 'ER PILIC'], []),
    ('DARDANEL', ['DARDANEL'], []),
    ('TONNY', ['TONNY BALIK'], []),
    ('UNO', ['UNO EKMEK', 'UNO TOST', 'UNO SANDVİÇ', 'UNO KRUVASAN', 'UNO'], []),
    ('DEDEOĞLU', ['DEDEOĞLU', 'DEDEOGLU'], []),
    ('GÜNAYDIN', ['GÜNAYDIN', 'GUNAYDIN'], []),
    ('BAĞCI', ['BAĞCI', 'BAGCI'], []),
    ('MARMARABİRLİK', ['MARMARABİRLİK', 'MARMARABIRLIK'], []),
    ('FORA', ['FORA ZEYTİN', 'FORA'], []),
    ('CEM', ['CEM ZEYTİN'], []),
    ('YARENLER', ['YARENLER'], []),
    ('ÖZBEY', ['ÖZBEY', 'OZBEY'], []),
    ('ÇİÇEK BALI', ['BEYŞEHİR', 'BEYSEHIR'], []),
    ('PAŞABAHÇE', ['PAŞABAHÇE', 'PASABAHCE'], []),
    ('LAV', ['LAV CAM', 'LAV BARDAK', 'LAV KASE'], []),
    ('GÜRALLAR', ['GÜRALLAR', 'GURAL'], []),
    ('FELİX', ['FELİX', 'FELIX'], []),
    ('WHİSKAS', ['WHİSKAS', 'WHISKAS'], []),
    ('PEDİGREE', ['PEDİGREE', 'PEDIGREE'], []),
    ('GOURMET', ['GOURMET GOLD', 'GOURMET PERLE', 'GOURMET'], []),
    ('FRISKIES', ['FRISKIES', 'FRİSKİES'], []),
    ('PRO PLAN', ['PRO PLAN', 'PROPLAN'], []),
    ('REFLEX', ['REFLEX'], []),
    ('MİS', ['MİS SÜT', 'MIS SUT', 'MİS'], []),
    ('VATAN', ['VATAN CİN MISIR', 'VATAN'], []),
    ('SEBİL', ['SEBİL CİN MISIR', 'SEBİL', 'SEBIL'], []),
    ('CHOCEUR', ['CHOCEUR'], []),
    ('MILKA', ['MİLKA', 'MILKA'], []),
    ('TOBLERONE', ['TOBLERONE'], []),
    ('NUTELLA', ['NUTELLA'], []),
    ('KİNDER', ['KİNDER', 'KINDER', 'KINDER BUENO', 'KINDER JOY', 'KINDER SURPRISE'], []),
    ('FERRERO', ['FERRERO', 'ROCHER', 'RAFFAELLO'], []),
    ('SNICKERS', ['SNICKERS'], []),
    ('TWIX', ['TWIX'], []),
    ('BOUNTY', ['BOUNTY'], []),
    ('MARS', ['MARS ÇİKOLATA'], []),
    ('M&M', ['M&M', 'M&M\'S', 'M AND M'], []),
    ('SKITTLES', ['SKITTLES'], []),
    ('ZÜBER', ['ZÜBER', 'ZUBER'], []),
    ('FİTPO', ['FİTPO', 'FITPO'], []),
    ('KROKAN', ['KROKAN'], []),
    ('TADELLE', ['TADELLE'], []),
    ('SARELLE', ['SARELLE'], []),
    ('GOL', ['GOL GOFRET', 'GOL'], []),
    ('COSBY', ['COSBY'], []),
    ('PAPİLİON', ['PAPİLİON', 'PAPILION'], []),
    ('DEEP FRESH', ['DEEP FRESH', 'DEEPFRESH'], []),
    ('FRESHMAKER', ['FRESHMAKER'], []),
    ('WET WIPES', ['WET WIPES'], []),
    ('UNİ', ['UNİ BABY', 'UNI BABY', 'UNİ', 'UNI'], []),
    ('ACTİVEX', ['ACTİVEX', 'ACTIVEX'], []),
    ('TOFFİFEE', ['TOFFİFEE', 'TOFFIFEE'], []),
    ('MERCI', ['MERCI'], []),
    ('GODİVA', ['GODİVA', 'GODIVA'], []),
    ('RITTER SPORT', ['RITTER SPORT', 'RİTTER SPORT'], []),
    ('POKEMON', ['POKEMON'], []),
    ('HOT WHEELS', ['HOT WHEELS', 'HOTWHEELS'], []),
    ('BARBIE', ['BARBIE', 'BARBİE'], []),
    ('FISHER-PRICE', ['FISHER-PRICE', 'FISHER PRICE'], []),
    ('MATCHBOX', ['MATCHBOX'], []),
    ('LEGO', ['LEGO'], []),
    ('MARLBORO', ['MARLBORO', 'TOUCH', 'EDGE'], []),
    ('PARLIAMENT', ['PARLIAMENT', 'PARLIAMENT NIGHT', 'AQUA BLUE', 'MIDNIGHT BLUE'], []),
    ('WINSTON', ['WINSTON', 'WINSTON SLENDER', 'WINSTON DARK', 'WINSTON XSENCE'], []),
    ('CAMEL', ['CAMEL', 'CAMEL YELLOW', 'CAMEL DEEP', 'CAMEL SLENDER'], []),
    ('ROTHMANS', ['ROTHMANS'], []),
    ('CHESTERFIELD', ['CHESTERFIELD'], []),
    ('MONTE CARLO', ['MONTE CARLO', 'MONTECARLO'], []),
    ('MURATTI', ['MURATTI', 'ROSSO'], []),
    ('LARK', ['LARK'], []),
    ('KENT', ['KENT SWITCH', 'KENT BLUE', 'KENT WHITE', 'KENT D-RANGE', 'KENT SLIMS', 'KENT SLENDER', 'KENT DRANGE'], []),
    ('PRESIDENT', ['PRESIDENT', 'PRESİDENT'], []),
    ('WINNER', ['WINNER', 'WİNNER'], []),
    ('HD', ['HD SİGARA', 'HD SLIMS', 'HD BLUE', 'HD RED'], []),
    ('VICEROY', ['VICEROY'], []),
    ('WEST', ['WEST SİGARA', 'WEST NAVY', 'WEST GREY', 'WEST GR', 'WEST RED'], []),
    ('ESSE', ['ESSE BLACK', 'ESSE SİGARA', 'ESSE'], []),
    ('POLO', ['POLO SİGARA', 'POLO SLIMS'], []),
    ('RAISON', ['RAISON'], []),
    ('MEDİCİNE', ['MEDİCİNE', 'MEDICINE'], []),
    ('TOROS', ['TOROS 2005', 'TOROS'], []),
    ('SAMSUN', ['SAMSUN 216', 'SAMSUN'], []),
    ('MALTEPE', ['MALTEPE'], []),
    ('TEKEL 2000', ['TEKEL 2000', 'TEKEL 2001', 'TEKEL'], []),
]

def classify_product_brand(title, current_brand):
    if not title:
        return current_brand or 'DİĞER'
    
    t_clean = title.upper().strip()
    
    # Check each brand rule in priority order
    for brand_name, keywords, excludes in BRAND_RULES:
        # Check excludes first
        has_exclude = False
        for ex in excludes:
            if ex in t_clean:
                has_exclude = True
                break
        if has_exclude:
            continue
            
        # Check keywords
        for kw in keywords:
            # Word boundary matching
            pattern = r'(?:^|[\s\-_.,/])' + re.escape(kw) + r'(?:$|[\s\-_.,/])'
            if re.search(pattern, t_clean):
                return brand_name

    # If starts with word and length >= 3, check current brand
    if current_brand and current_brand not in ['DİĞER', 'DIGER', 'YARENLER', 'CİPS', 'SİGARA', 'ÇAY', 'SU', 'SODA', 'OYUNCAK', 'KAHVE', 'TURKİYE', 'TÜRKİYE']:
        return current_brand
        
    return 'DİĞER'

# Test classifications
changes = []
for p in products:
    curr = p.get('brand', 'DİĞER')
    new_b = classify_product_brand(p.get('title', ''), curr)
    if new_b != curr:
        changes.append((p.get('title'), curr, new_b))

print(f"Toplam Değiştirilen / Düzeltilen Marka: {len(changes)}")
print("\nÖrnek Düzeltmeler:")
for t, old_b, new_b in changes[:35]:
    print(f"  Ürün: '{t}'\n     Eski Marka: [{old_b}]  ➔  Yeni Doğru Marka: [{new_b}]\n")
